# This is a basic workflow to help you get started with Actions

name: Publish PDFs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "fix-images-2" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  convert-constitution:
    name: Build Constitution PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: constitution.md
          images_dir: assets
          output_dir: pdfs
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v7
        with:
          name: constitution
          path: pdfs/constitution.pdf
          archive: false
  convert-standing-orders:
    name: Build Standing Orders PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: standing-orders.md
          images_dir: assets
          output_dir: pdfs
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v7
        with:
          name: standing-orders
          path: pdfs/standing-orders.pdf
          archive: false
